spring:
  application:
    name: authentication
  data:
    mongodb:
      database: userdb
      username: user
      password: password
      host: localhost
      port: 27017
      authentication-database: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 9999
jwt:
  secret: s3cr3t
  expiration: 1h